#!/usr/bin/env bash
# Display information about subdomains


get_subdomain_info(){
	parse_info=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' ' '| cut -d ' ' -f 4- | tr '\n' ' ')
	echo "$2 $parse_info" | awk '{print "The subdomain " $1" is a " $2 " record and points to " $3}' 
}

if [ "$#" -eq 1 ]
then
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"
	do
		get_subdomain_info "$1" "$subdomain"
	done
elif [ "$#" -eq 2 ]
then
	get_subdomain_info "$1" "$2"
fi
