#!/usr/bin/env bash
# Fix this container
# so that Nginx is running as the nginx user
id -u nginx &>/dev/null || adduser --system --no-create-home --disabled-login --disabled-password --group nginx
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /etc/nginx
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       .*/listen 8080;/' /etc/nginx/nginx.conf
service nginx restart

